set(headers ${headers}
	include/ConsoleUtilSSE.h
	src/Achievement.h
	src/AchievementManager.h
	src/AchievementMenu.h
	src/AchievementWidget.h
	src/CommonFunctions.h
	src/Conditions/AchievementUnlocked/AchievementUnlockedCondition.h
	src/Conditions/ActorDeath/ActorDeathCondition.h
	src/Conditions/BaseActorDeath/BaseActorDeathCondition.h
	src/Conditions/BookRead/BookReadCondition.h
	src/Conditions/Condition.h
	src/Conditions/ObjectState/ObjectStateCondition.h
	src/Conditions/DragonSoulAbsorbed/DragonSoulsAbsorbedCondition.h
	src/Conditions/DungeonCleared/DungeonClearedCondition.h
	src/Conditions/GlobalVariableState/GlobalVariableStateCondition.h
	src/Conditions/ItemCrafted/ItemCraftedCondition.h
	src/Conditions/ItemInInventory/ItemInInventoryCondition.h
	src/Conditions/LocationDiscovery/LocationDiscoveryCondition.h
	src/Conditions/PapyrusBinding/PapyrusBindingCondition.h
	src/Conditions/PlayerActivation/PlayerActivationCondition.h
	src/Conditions/PlayerFirstEnterCell/PlayerFirstEnterCellCondition.h
	src/Conditions/PlayerLevel/PlayerLevelCondition.h
	src/Conditions/QueryStatValue/QueryStatValueCondition.h
	src/Conditions/QuestObjectiveDone/QuestObjectiveDoneCondition.h
	src/Conditions/QuestStageDone/QuestStageDoneCondition.h
	src/Conditions/ShoutLearned/ShoutLearnedCondition.h
	src/Conditions/SkillLevel/SkillLevelCondition.h
	src/Conditions/SpellLearned/SpellLearnedCondition.h
	src/ConditionsJoinType.h
	src/CustomRE.h
	src/EventProcessor.h
	src/KeyMapping.h
	src/LocalizationManager.h
	src/MessageBox.h
	src/PCH.h
	src/Papyrus.h
	src/Runnable.h
	src/Scaleform.h
	src/Serializer.h
	src/Singleton.h
	src/Sync.h
	src/UIManager.h
	src/Utility.h
	src/log.h
	src/settings.h
	src/util.h
)
