set(sources ${sources}
	src/Achievement.cpp
	src/AchievementManager.cpp
	src/AchievementMenu.cpp
	src/AchievementWidget.cpp
	src/CommonFunctions.cpp
	src/Conditions/ObjectState/ObjectStateCondition.cpp
	src/Conditions/AchievementUnlocked/AchievementUnlockedCondition.cpp
	src/Conditions/ActorDeath/ActorDeathCondition.cpp
	src/Conditions/BaseActorDeath/BaseActorDeathCondition.cpp
	src/Conditions/BookRead/BookReadCondition.cpp
	src/Conditions/Condition.cpp
	src/Conditions/DragonSoulAbsorbed/DragonSoulsAbsorbedCondition.cpp
	src/Conditions/DungeonCleared/DungeonClearedCondition.cpp
	src/Conditions/GlobalVariableState/GlobalVariableStateCondition.cpp
	src/Conditions/ItemCrafted/ItemCraftedCondition.cpp
	src/Conditions/ItemInInventory/ItemInInventoryCondition.cpp
	src/Conditions/LocationDiscovery/LocationDiscoveryCondition.cpp
	src/Conditions/PapyrusBinding/PapyrusBindingCondition.cpp
	src/Conditions/PlayerActivation/PlayerActivationCondition.cpp
	src/Conditions/PlayerFirstEnterCell/PlayerFirstEnterCellCondition.cpp
	src/Conditions/PlayerLevel/PlayerLevelCondition.cpp
	src/Conditions/QueryStatValue/QueryStatValueCondition.cpp
	src/Conditions/QuestObjectiveDone/QuestObjectiveDoneCondition.cpp
	src/Conditions/QuestStageDone/QuestStageDoneCondition.cpp
	src/Conditions/ShoutLearned/ShoutLearnedCondition.cpp
	src/Conditions/SkillLevel/SkillLevelCondition.cpp
	src/Conditions/SpellLearned/SpellLearnedCondition.cpp
	src/CustomRE.cpp
	src/EventProcessor.cpp
	src/LocalizationManager.cpp
	src/Papyrus.cpp
	src/Runnable.cpp
	src/Serializer.cpp
	src/Settings.cpp
	src/Sync.cpp
	src/UIManager.cpp
	src/Utility.cpp
	src/log.cpp
	src/plugin.cpp
)
